"""add_platform_revenue_table

Revision ID: 9405ac675852
Revises: 8b2084d5874e
Create Date: 2026-02-23 19:04:43.912527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9405ac675852'
down_revision: Union[str, Sequence[str], None] = '8b2084d5874e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_revenue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_revenue_agent_id'), 'platform_revenue', ['agent_id'], unique=False)
    op.create_index(op.f('ix_platform_revenue_transaction_id'), 'platform_revenue', ['transaction_id'], unique=False)
    op.alter_column('agents', 'auto_approve_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False,
               existing_server_default=sa.text('10.0000'))
    op.drop_constraint(op.f('transactions_idempotency_key_key'), 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.create_unique_constraint(op.f('transactions_idempotency_key_key'), 'transactions', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('agents', 'auto_approve_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True,
               existing_server_default=sa.text('10.0000'))
    op.drop_index(op.f('ix_platform_revenue_transaction_id'), table_name='platform_revenue')
    op.drop_index(op.f('ix_platform_revenue_agent_id'), table_name='platform_revenue')
    op.drop_table('platform_revenue')
    # ### end Alembic commands ###
